### ISSUE TITLE
Fontes de dados a respeito dos vazamentos

### ISSUE THREAD

**Issue by dmesquita** [ThadeuLuz/oleo-no-nordeste#1]
Oi, parabéns e obrigada por iniciar o projeto!!

Tu tá pegando os dados sobre os vazamentos das praias onde? Tu sabe de mais fontes de dados sobre os vazamentos? Eu trabalho com data science, queria ver se dava pra ajudar com algo na estratégia (previsão de chegadas em outras praias, tentar descobrir de onde o óleo vem essas coisas).

**Comment by enieber** [comment]
@dmesquita acho que a fonte de dados é o [IBAMA](https://www.ibama.gov.br/notas/2047-manchas-de-oleo-no-litoral-do-nordeste) segundo o site
